import pyautogui
import time
time.sleep(4)
for i in range(30):
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(0, 65, duration=0.1)
        pyautogui.mouseUp(duration=0.1)
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(-65, 0, duration=0.1)
        pyautogui.mouseUp(duration=0.1)
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(-65, 0, duration=0.1)
        pyautogui.mouseUp(duration=0.1)
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(0, -65, duration=0.1)
        pyautogui.mouseUp(duration=0.1)
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(0, -65, duration=0.1)
        pyautogui.mouseUp(duration=0.1)
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(65, 0, duration=0.1)
        pyautogui.mouseUp(duration=0.1)
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(65, 0, duration=0.1)
        pyautogui.mouseUp(duration=0.1)
        pyautogui.mouseDown(button='left',duration=0.1)
        pyautogui.moveRel(0, 65, duration=0.1)
        pyautogui.mouseUp(duration=0.1)